#!/usr/bin/env bash

set -e

usage () {
  echo "Usage: avm <make target>"
}

# Default values for environment variables
CONTAINER_RUNTIME=${CONTAINER_RUNTIME:-"docker"}
CONTAINER_IMAGE=${CONTAINER_IMAGE:-"mcr.microsoft.com/azterraform:avm-latest"}
CONTAINER_PULL_POLICY=${CONTAINER_PULL_POLICY:-"always"}
MAKEFILE_REF=${MAKEFILE_REF:-"main"}
PORCH_REF=${PORCH_REF:-"main"}

if [ ! "$(command -v "${CONTAINER_RUNTIME}")" ]; then
    echo "Error: ${CONTAINER_RUNTIME} is not installed. Please install ${CONTAINER_RUNTIME} first."
    exit 1
fi

if [ -z "$1" ]; then
    echo "Error: Please provide a make target. See https://github.com/Azure/avm-terraform-governance/blob/main/Makefile for available targets."
    echo
    usage
    exit 1
fi

# Check if AZURE_CONFIG_DIR is set, if not, set it to ~/.azure
if [ -z "${AZURE_CONFIG_DIR}" ]; then
  AZURE_CONFIG_DIR="${HOME}/.azure"
fi

# Check if AZURE_CONFIG_DIR exists, if it does, mount it to the container
if [ -d "${AZURE_CONFIG_DIR}" ]; then
  AZURE_CONFIG_MOUNT="-v ${AZURE_CONFIG_DIR}:/home/runtimeuser/.azure"
fi

# If we are not in GitHub Actions and NO_COLOR is not set, we want to use TUI and interactive mode
if [ -z "${GITHUB_RUN_ID}" ] && [ -z "${NO_COLOR}" ]; then
  TUI="--tui"
  DOCKER_INTERACTIVE="-it"
  export FORCE_COLOR=1
fi

# if PORCH_BASE_URL is set, we want to add it to the make command
if [ -n "${PORCH_BASE_URL}" ]; then
  PORCH_BASE_URL_MAKE_ADD="PORCH_BASE_URL=${PORCH_BASE_URL}"
fi

# Check if we are running in a container
# If we are then just run make directly
if [ -z "${AVM_IN_CONTAINER}" ]; then
  ${CONTAINER_RUNTIME} run \
    --pull "${CONTAINER_PULL_POLICY}" \
    --user "$(id -u):$(id -g)" \
    --rm \
    ${DOCKER_INTERACTIVE} \
    -v "$(pwd)":/src \
    ${AZURE_CONFIG_MOUNT:-} \
    -e ARM_CLIENT_ID \
    -e ARM_OIDC_REQUEST_TOKEN \
    -e ARM_OIDC_REQUEST_URL \
    -e ARM_SUBSCRIPTION_ID \
    -e ARM_TENANT_ID \
    -e ARM_USE_OIDC \
    -e AVM_EXAMPLE \
    -e CONFTEST_APRL_URL \
    -e CONFTEST_AVMSEC_URL \
    -e CONFTEST_EXCEPTIONS_URL \
    -e FORCE_COLOR \
    -e GITHUB_TOKEN \
    -e GREPT_URL \
    -e MPTF_URL \
    -e NO_COLOR \
    -e PORCH_LOG_LEVEL \
    -e TEST_TYPE \
    -e TF_IN_AUTOMATION=1 \
    -e TFLINT_CONFIG_URL \
    --env-file <(env | grep '^TF_VAR_') \
    "${CONTAINER_IMAGE}" \
    make \
    TUI="${TUI}" \
    MAKEFILE_REF="${MAKEFILE_REF}" \
    "${PORCH_BASE_URL_MAKE_ADD}" \
    PORCH_REF="${PORCH_REF}" \
    "$1"
else
  make TUI="${TUI}" MAKEFILE_REF="${MAKEFILE_REF}" "${PORCH_BASE_URL_MAKE_ADD}" PORCH_REF="${PORCH_REF}" "$1"
fi
