---
name: e2e test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  getexamples:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.getexamples.outputs.examples }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: get examples
        id: getexamples
        run: |
          go install github.com/matt-FFFFFF/jsonls@v0.1.0
          echo examples="$(jsonls -d)" >> "$GITHUB_OUTPUT"
        working-directory: examples
  testexamples:
    runs-on: ubuntu-latest
    needs: getexamples
    environment: test
    strategy:
      matrix:
        example: ${{ fromJson(needs.getexamples.outputs.examples) }}
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
          cd examples/${{ matrix.example }}
          terraform init
          terraform apply -auto-approve
          PLANEXIT=$(terraform plan -detailed-exitcode)
          if [ $PLANEXIT -eq 2 ]; then
            echo "Example not idempotent"
            terraform destroy
            exit 1
          fi
          terraform destroy
