---
name: e2e test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  getexamples:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.getexamples.outputs.examples }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: get examples
        id: getexamples
        run: |
          go install github.com/matt-FFFFFF/jsonls@v0.1.0
          echo examples="$(jsonls -d)" >> "$GITHUB_OUTPUT"
        working-directory: examples

  testexamples:
    runs-on: ubuntu-latest
    needs: getexamples
    environment: test
    env:
      TF_IN_AUTOMATION: 1
    strategy:
      matrix:
        example: ${{ fromJson(needs.getexamples.outputs.examples) }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '>=1.5.0'

      - uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform init
        run: terraform init
        working-directory: examples/${{ matrix.example }}

      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: examples/${{ matrix.example }}

      - name: terraform plan
        id: plan
        run: |
          terraform plan -detailed-exitcode
          echo PLANCODE="$?" >> "$GITHUB_OUTPUT"
        continue-on-error: true
        working-directory: examples/${{ matrix.example }}

      - name: check idempotent
        run: |
          echo Error: terraform plan code is ${{ steps.plan.outputs.PLANCODE }}
          exit 1
        working-directory: examples/${{ matrix.example }}
        if: steps.plan.outputs.PLANCODE != 0

      - name: terraform destroy
        run: terraform destroy -auto-approve
        working-directory: examples/${{ matrix.example }}
        if: always()
